services:
  - type: web
    name: sie-chabad-demo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python demo_proxy.py"
    envVars:
      - key: PORT
        value: 10000